python test_large_scale.py --num_subjects 10 --noise_level 2 --kernel_length 50 --title 'compare_N10_KL50_NL2_'
#python test_large_scale.py --num_subjects 10 --noise_level 1 --kernel_length 50 --title 'compare_N10_KL50_NL1_'
#python test_large_scale.py --num_subjects 10 --noise_level 5 --kernel_length 50 --title 'compare_N10_KL50_NL5_'
#python test_large_scale.py --num_subjects 10 --noise_level 10 --kernel_length 50 --title 'compare_N10_KL50_NL10_'
#python test_large_scale.py --num_subjects 10 --noise_level 100 --kernel_length 50 --title 'compare_N10_KL50_NL100_'

python test_large_scale.py --num_subjects 20 --noise_level 2 --kernel_length 50 --title 'compare_N20_KL50_NL2_'
#python test_large_scale.py --num_subjects 20 --noise_level 1 --kernel_length 50 --title 'compare_N20_KL50_NL1_'
#python test_large_scale.py --num_subjects 20 --noise_level 5 --kernel_length 50 --title 'compare_N20_KL50_NL5_'
#python test_large_scale.py --num_subjects 20 --noise_level 10 --kernel_length 50 --title 'compare_N20_KL50_NL10_'
#python test_large_scale.py --num_subjects 20 --noise_level 100 --kernel_length 50 --title 'compare_N20_KL50_NL100_'

python test_large_scale.py --num_subjects 30 --noise_level 2 --kernel_length 50 --title 'compare_N30_KL50_NL2_'
#python test_large_scale.py --num_subjects 30 --noise_level 1 --kernel_length 50 --title 'compare_N30_KL50_NL1_'
#python test_large_scale.py --num_subjects 30 --noise_level 5 --kernel_length 50 --title 'compare_N30_KL50_NL5_'
#python test_large_scale.py --num_subjects 30 --noise_level 10 --kernel_length 50 --title 'compare_N30_KL50_NL10_'
#python test_large_scale.py --num_subjects 30 --noise_level 100 --kernel_length 50 --title 'compare_N30_KL50_NL100_'

python test_large_scale.py --num_subjects 40 --noise_level 2 --kernel_length 50 --title 'compare_N40_KL50_NL2_'
#python test_large_scale.py --num_subjects 40 --noise_level 1 --kernel_length 50 --title 'compare_N40_KL50_NL1_'
#python test_large_scale.py --num_subjects 40 --noise_level 5 --kernel_length 50 --title 'compare_N40_KL50_NL5_'
#python test_large_scale.py --num_subjects 40 --noise_level 10 --kernel_length 50 --title 'compare_N40_KL50_NL10_'
#python test_large_scale.py --num_subjects 40 --noise_level 100 --kernel_length 50 --title 'compare_N40_KL50_NL100_'

python test_large_scale.py --num_subjects 50 --noise_level 1 --kernel_length 50 --title 'compare_N50_KL50_NL1_'
#python test_large_scale.py --num_subjects 50 --noise_level 2 --kernel_length 50 --title 'compare_N50_KL50_NL2_'
#python test_large_scale.py --num_subjects 50 --noise_level 5 --kernel_length 50 --title 'compare_N50_KL50_NL5_'
#python test_large_scale.py --num_subjects 50 --noise_level 10 --kernel_length 50 --title 'compare_N50_KL50_NL10_'
#python test_large_scale.py --num_subjects 50 --noise_level 100 --kernel_length 50 --title 'compare_N50_KL50_NL100_'
